theme: just-the-docs
color_scheme: purple
repository: ngoanh2n/blog

title: ngoanh2n
url: "https://ngoanh2n.github.io"
permalink: pretty
favicon_ico: "/assets/favicon.ico"

gh_edit_link: true
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ngoanh2n/blog"

collections:
  posts:
    output: true
    permalink: "/:posts/:path/"

just_the_docs:
  collections:
    posts:
      name: Posts
      nav_fold: true
      nav_exclude: true
      search_exclude: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/posts/page:num/"