theme: just-the-docs
color_scheme: purple
# logo: "/assets/favicon.ico"
baseurl: "/blog"
permalink: pretty
title: ngoanh2n's blog
repository: ngoanh2n/blog
favicon_ico: "/assets/favicon.ico"
url: "https://ngoanh2n.github.io/blog"
