theme: just-the-docs
color_scheme: purple
repository: ngoanh2n/blog

title: ngoanh2n
url: "https://ngoanh2n.github.io"
permalink: pretty
favicon_ico: "/assets/favicon.ico"

gh_edit_link: true
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ngoanh2n/blog"

collections:
  posts:
    output: true
    permalink: "/:posts/:path/"

just_the_docs:
  collections:
    posts:
      name: Posts
      nav_fold: true
      nav_exclude: true
      search_exclude: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

paginate: 5
paginate_path: "/posts/page:num/"