theme: just-the-docs
title: ngoanh2n's blog
# logo: "/assets/favicon.ico"
permalink: pretty
baseurl: "/blog"
repository: ngoanh2n/blog
favicon_ico: "/assets/favicon.ico"
url: "https://ngoanh2n.github.io/blog"
